default_options = {
    "time": {
        "duration": 0.0,
        "hydraulic_timestep": 3600,
        "quality_timestep": 360,
        "rule_timestep": 360,
        "pattern_timestep": 3600,
        "pattern_start": 0.0,
        "report_timestep": 3600,
        "report_start": 0.0,
        "start_clocktime": 0.0,
        "statistic": "NONE",
        "pattern_interpolation": False,
    },
    "hydraulic": {
        "headloss": "H-W",
        "hydraulics": None,
        "hydraulics_filename": None,
        "viscosity": 1.0,
        "specific_gravity": 1.0,
        "pattern": "1",
        "demand_multiplier": 1.0,
        "demand_model": "DDA",
        "minimum_pressure": 0.0,
        "required_pressure": 0.07,
        "pressure_exponent": 0.5,
        "emitter_exponent": 0.5,
        "trials": 200,
        "accuracy": 0.001,
        "unbalanced": "STOP",
        "unbalanced_value": None,
        "checkfreq": 2,
        "maxcheck": 10,
        "damplimit": 0.0,
        "headerror": 0.0,
        "flowchange": 0.0,
        "inpfile_units": "GPM",
        "inpfile_pressure_units": None,
    },
    "report": {
        "pagesize": None,
        "report_filename": None,
        "status": "NO",
        "summary": "YES",
        "energy": "NO",
        "nodes": False,
        "links": False,
        "report_params": {
            "elevation": False,
            "demand": True,
            "head": True,
            "pressure": True,
            "quality": True,
            "length": False,
            "diameter": False,
            "flow": True,
            "velocity": True,
            "headloss": True,
            "position": False,
            "setting": False,
            "reaction": False,
            "f-factor": False,
        },
    },
    "quality": {
        "parameter": "NONE",
        "trace_node": None,
        "chemical_name": "CHEMICAL",
        "diffusivity": 1.0,
        "tolerance": 0.01,
        "inpfile_units": "mg/L",
    },
    "reaction": {
        "bulk_order": 1.0,
        "wall_order": 1.0,
        "tank_order": 1.0,
        "bulk_coeff": 0.0,
        "wall_coeff": 0.0,
        "limiting_potential": None,
        "roughness_correl": None,
    },
    "energy": {"global_price": 0, "global_pattern": None, "global_efficiency": None, "demand_charge": None},
    "graphics": {
        "dimensions": None,
        "units": "NONE",
        "offset": None,
        "image_filename": None,
        "map_filename": None,
    },
    "user": {},
}
